### ISSUE TITLE
auro-background: code snippet for the fixed width and height example

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-background#11]
## Describe the bug

The code example for the fixed width and height example doesn't show how to use width or height.

## To Reproduce

1. Go to the demo page and look at the code examples and ensure they are correct.

**Comment by blackfalcon** [comment]
I don't think this needs to be bound to the v2.1 release. A document update has no impact on the element's features and will not create a version change. 

We should always correct document updates and push ASAP.

**Comment by jason-capsule42** [comment]
@braven112 Do you agree with doing this as a one off immediate update to the repo?
