### ISSUE TITLE
auro-background: use of deprecated @alaskaairux/webcorestylesheets@3.7.3

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-background#14]
# General Support Request
This component has a dependency on a deprecated version of the wcss.

Please update from @alaskaairux/webcorestylesheets@3.7.3 to latest (@aurodesignsystem/webcorestylesheets@5.0.4 or later)

**Comment by blackfalcon** [comment]
This issue was addressed within the scope of this duplicate issue. 

- https://github.com/AlaskaAirlines/auro-background/issues/15
