### ISSUE TITLE
auro-background: Import issue in Svelte 

### ISSUE THREAD

**Issue by fajar-apri-alaska** [AlaskaAirlines/auro-background#20]
## Describe the bug

I have been doing some task that would load `auro-background` in [SvelteKit](https://kit.svelte.dev/) framework, and found that `auro-background` doesn't render the background image when importing using npm package per below screenshot:

<img width="1079" alt="image" src="https://github.com/AlaskaAirlines/auro-background/assets/124668226/be9de9b1-4b4b-4aee-8024-9b878921ef06">

## To Reproduce

1. Create a minimum svelte project using [SvelteKit: Creating a Project](https://kit.svelte.dev/docs/creating-a-project),
2. `npm install @aurodesignsystem/auro-background` (with latest WCSS also).
3. Use the code from Auro doc site (or copy below):
```
// +page.svelte

// optional, not in the scope of issue
import @aurodesignsystem/auro-header;
import @aurodesignsystem/auro-hyperlink;

// required
import @aurodesignsystem/auro-background;

...

<auro-background bg="url(https://sitecore-test-single-westus2.azurewebsites.net/-/media/Images/pages/examples/ad2) center 
center/cover no-repeat">
  <div style="color: var(--ds-color-text-primary-default); display: flex; flex-direction: column; align-items: center; justify-content: center;">
    <auro-header level="2" display="600">View all destinations</auro-header>
    <auro-hyperlink cta href="#">See where we fly</auro-hyperlink>
  </div>
</auro-background>
```

## Expected behavior

From the render result, it turns out the `style` inside the shadowRoot doesn't return as string after being processed by `styleMap` function (or maybe it doesn't get processed by the `styleMap` at all):

<img width="1079" alt="image" src="https://github.com/AlaskaAirlines/auro-background/assets/124668226/6a1c6af0-07a5-4c8c-9b4a-4758a991c921">

---

After doing some research, I tried using bundled version when importing:
`import @aurodesignsystem/auro-background/dist/auro-background__bundled.js;`
instead of
`import @aurodesignsystem/auro-background;`

And somehow it works when using above imports per below screenshot:
<img width="1079" alt="image" src="https://github.com/AlaskaAirlines/auro-background/assets/124668226/bea5e4d4-b8d1-4f29-9ce4-62821f89218b">

Also the `styleMap` is working:
<img width="1079" alt="image" src="https://github.com/AlaskaAirlines/auro-background/assets/124668226/407e30ad-71c3-47a5-a198-e754a25b1603">

## Desktop (please complete the following information):

 - OS: MacOS Ventura 13.6.3 (22G436)
 - Browser Chrome
 - Version 120.0.6099.199 (Official Build) (x86_64)

## Smartphone (please complete the following information):

none

## Additional context

maybe related, but some error I got while researching:
<img width="495" alt="image" src="https://github.com/AlaskaAirlines/auro-background/assets/124668226/dbc514ac-f3af-405f-9c65-d5c1c2b69e59">

tried out manually edit the reference directly inside node_modules to:
`import { styleMap } from 'lit-html/directives/style-map.js';`
removes the error log, but it doesn't solve the issue.

`import { styleMap } from 'lit/directives/style-map.js';`
doesn't solve the issue either.

**Comment by blackfalcon** [comment]
See this PR https://github.com/AlaskaAirlines/auro-background/pull/24

**Comment by blackfalcon** [comment]
The above-linked PR is designed to make the whole element ES6 compatible. I am curious what pointed you to use `import @aurodesignsystem/auro-background/dist/auro-background__bundled.js;`.

**Comment by fajar-apri-alaska** [comment]
> The above-linked PR is designed to make the whole element ES6 compatible. I am curious what pointed you to use `import @aurodesignsystem/auro-background/dist/auro-background__bundled.js;`.

I'm not sure, to be honest I am just trying out everything.

**Comment by fajar-apri-alaska** [comment]
Closing since PR #24 merged.
